spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PROJECT_01
    username: jh950925
    password: rla123

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update # 어떤 방식 으로 테이블 생성 할 것인지
    properties:
      hibernate:
        highlight_sql: true # 색상 변경
        format_sql: true    # 쿼리 출력 할 것인지
        show_sql: true      # 쿼리 추력
        use_sql_comments: true  # 주석 출력